version: '2'
services:
    web:
        build: nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - api

    api:
        build: .
        ports:
            - "5012:5012"
        volumes:
            - .:/app
